### PR TITLE
Feat(Manual): Add written example Traefik Middleware

### PR DESCRIPTION
**Pull request by StevenMcElligott**
**Description**

Add more info to the Traefik Middleware page and an example of Basic Auth

⚒️ Fixes  # 

**⚙️ Type of change**

- [X] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**📃 Notes:**

**✔️ Checklist:**

- [X] ⚖️ My code follows the style guidelines of this project
- [X] 👀 I have performed a self-review of my own code
- [X] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [X] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic versioning

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🪞 I have opened a PR on [truecharts/containers](https://github.com/truecharts/containers) adding the container to TrueCharts mirror repo.
- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

### CODE REVIEW

**Review by Ornias1993 — CHANGES_REQUESTED** [review]
Can you move this to the traefik docs please?

**Comment by StevenMcElligott** [comment]
This already close, I’ll close this PR

**Review by Ornias1993 — APPROVED** [review]

**Comment by StevenMcElligott** [comment]
Just thought you want to keep the video there alone? Maybe remove it from the Manual section entirely?

**Comment by Ornias1993** [comment]
@StevenMcElligott All traefik stuff needs to go into traefik app docs and removed from general guides.

**Comment by Ornias1993** [comment]
In the future i'm just going to make a single guide on our adviced stack, linking to the individual setup guides for the apps included in our "basic stack"

**Pull request closed without merging**
