### PR TITLE
Resources

### PR DESCRIPTION
**Pull request by stavros-k**
**Description**

⚒️ Fixes  # 

**⚙️ Type of change**

- [ ] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**📃 Notes:**

**✔️ Checklist:**

- [ ] ⚖️ My code follows the style guidelines of this project
- [ ] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic versioning

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

### CODE REVIEW

**Review by Ornias1993 — APPROVED** [review]

**Comment by stavros-k** [comment]
Removed the gpu from the top level resources.limits as the link goes to the resources.limits dict that show all other info as well

**Comment by Ornias1993** [comment]
> Removed the gpu from the top level resources.limits as the link goes to the resources.limits dict that show all other info as well

I really want to keep that there, as the examples are VITAL for thorough helm platform support

**Comment by stavros-k** [comment]
I'm the top level there isn't even the cpu, it says to see the available options go to this link/section

**Comment by Ornias1993** [comment]
> In the top level there isn't even the cpu, it says to see the available options go to this link/section

ahh shoot, good catch!

**Comment by stavros-k** [comment]
Okay I'm blind today I'll restore

**Comment by stavros-k** [comment]
Or just reword and actually point to the link.

**Pull request merged**
