### PR TITLE
Add text-based instructions to Installing Traefik

### PR DESCRIPTION
**Pull request by HumbleDeer**
**Description**

**⚙️ Type of change**

- [x] ⚙️ ~~Feature/App~~ Documentation addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**✔️ Checklist:**

- [x] ⚖️ My code follows the style guidelines of this project
- [x] 👀 I have performed a self-review of my own code
- [ ] ~~#️⃣ I have commented my code, particularly in hard-to-understand areas~~
- [x] 📄 I have made corresponding changes to the documentation
- [x] ⚠️ My changes generate no new warnings
- [ ] ~~🧪 I have added tests to this description that prove my fix is effective or that my feature works~~
- [ ] ~~⬆️ I increased versions for any altered app according to semantic versioning~~
---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

### CODE REVIEW

**Comment by HumbleDeer** [comment]
Since the CLA is so huge and I am blind, I will assume this document asks me to waive claiming rights.
My contribution is permitted to be used by TrueCharts without attribution or obligation towards me.

**Comment by HumbleDeer** [comment]
I had to pull the changes from the original upstream, but I'm not sure if that was the right thing to do. I'm not sure if it'd still be able to merge without it. Feedback welcome.

**Comment by Ornias1993** [comment]
Love this, but maybe we should move this to traefik specific docs as well to be honest?

**Comment by Ornias1993** [comment]
> Since the CLA is so huge and I am blind, I will assume this document asks me to waive claiming rights. My contribution is permitted to be used by TrueCharts without attribution or obligation towards me.

The CLA gives a prepetual and unlimited use right to the owner of the project (me and hopefully a seperate entity in the future).

**Comment by HumbleDeer** [comment]
> Love this, but maybe we should move this to traefik specific docs as well to be honest?

That's fine by me. :)



> > Since the CLA is so huge and I am blind, I will assume this document asks me to waive claiming rights. My contribution is permitted to be used by TrueCharts without attribution or obligation towards me.
> 
> The CLA gives a prepetual and unlimited use right to the owner of the project (me and hopefully a seperate entity in the future).

And I consent to this.

**Comment by stavros-k** [comment]
@HumbleDeer Just to avoid any confusion! You have to move this guide at https://github.com/truecharts/charts/tree/master/charts/stable/traefik/docs

Create a new file in this directory!

No rush ofc

**Comment by stavros-k** [comment]
> I'll leave the rest of these things up to other devs, since all I wanted to do was update the file that was there. I didn't add this file from scratch. I'm not that well at home in all the rest of this. Sorry!

Cool np! I'll move it there!

**Comment by HumbleDeer** [comment]
Changes are live on https://truecharts.org/docs/manual/SCALE%20Apps/installing-Traefik

**Pull request merged**
